### ISSUE TITLE
[-v] Debug pypy + imp

### ISSUE THREAD

**Issue by whit537** [whit537/cloud-custodian#10]
Kapil in Gitter:

> pypy seems to dislike the imp module usage in mu.py tests
> its failing the build on drone

**Comment by whit537** [comment]
https://ci.cloudcustodian.io/capitalone/cloud-custodian/1827

**Comment by whit537** [comment]
Why didn't drone catch this before?

**Comment by whit537** [comment]
```
$ brew install pypy
Updating Homebrew...
```

**Comment by whit537** [comment]
Okay, I can repro locally.

```
(env-pypy) $ nosetests -sv tests/test_mu.py
test_can_add_py_file (tests.test_mu.AddPyFile) ... ok
test_fails_if_py_not_available (tests.test_mu.AddPyFile) ... ok
test_reverts_to_py_if_available (tests.test_mu.AddPyFile) ... ok
test_class_constructor_only_accepts_py_modules_not_pyc (tests.test_mu.Constructor) ... ERROR
test_config_rule_evaluation (tests.test_mu.PolicyLambdaProvision) ... ok
test_config_rule_provision (tests.test_mu.PolicyLambdaProvision) ... ok
test_cwe_asg_instance (tests.test_mu.PolicyLambdaProvision) ... ok
test_cwe_instance (tests.test_mu.PolicyLambdaProvision) ... ok
test_cwe_schedule (tests.test_mu.PolicyLambdaProvision) ... ok
test_cwe_trail (tests.test_mu.PolicyLambdaProvision) ... ok
test_cwe_update_config_and_code (tests.test_mu.PolicyLambdaProvision) ... ok
test_cwl_subscriber (tests.test_mu.PolicyLambdaProvision) ... ok
test_mu_metrics (tests.test_mu.PolicyLambdaProvision) ... ok
test_sns_subscriber (tests.test_mu.PolicyLambdaProvision) ... ok
test_can_add_a_file_with_contents_from_a_string (tests.test_mu.PythonArchiveTest) ... ok
test_can_add_additional_files_while_open (tests.test_mu.PythonArchiveTest) ... ok
test_can_set_path_when_adding_files (tests.test_mu.PythonArchiveTest) ... ok
test_cant_add_contents_when_closed (tests.test_mu.PythonArchiveTest) ... ok
test_cant_add_files_when_closed (tests.test_mu.PythonArchiveTest) ... ok
test_cant_get_bytes_when_open (tests.test_mu.PythonArchiveTest) ... ok
test_custodian_archive_creates_a_custodian_archive (tests.test_mu.PythonArchiveTest) ... ok
test_even_unreadable_files_become_readable (tests.test_mu.PythonArchiveTest) ... ok
test_excludes_non_py_files (tests.test_mu.PythonArchiveTest) ... ok
test_files_are_all_readable (tests.test_mu.PythonArchiveTest) ... ok
test_handles_packages (tests.test_mu.PythonArchiveTest) ... ok
test_handles_stdlib_modules (tests.test_mu.PythonArchiveTest) ... ok
test_handles_third_party_modules (tests.test_mu.PythonArchiveTest) ... ok
test_unless_you_make_your_own_zipinfo (tests.test_mu.PythonArchiveTest) ... ok

======================================================================
ERROR: test_class_constructor_only_accepts_py_modules_not_pyc (tests.test_mu.Constructor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tests/test_mu.py", line 505, in test_class_constructor_only_accepts_py_modules_not_pyc
    self.assertTrue(get('bar'), 'bar.pyc')
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tests/test_mu.py", line 503, in <lambda>
    get = lambda name: os.path.basename(imp.find_module(name)[1])
ImportError: No module named bar

----------------------------------------------------------------------
Ran 28 tests in 2.878s

FAILED (errors=1)
```

**Comment by whit537** [comment]
Interestingly, it passes with `pytest`!

```
(env-pypy) $ nosetests tests/test_mu.py:Constructor
E
======================================================================
ERROR: test_class_constructor_only_accepts_py_modules_not_pyc (tests.test_mu.Constructor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tests/test_mu.py", line 505, in test_class_constructor_only_accepts_py_modules_not_pyc
    self.assertTrue(get('bar'), 'bar.pyc')
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tests/test_mu.py", line 503, in <lambda>
    get = lambda name: os.path.basename(imp.find_module(name)[1])
ImportError: No module named bar

----------------------------------------------------------------------
Ran 1 test in 0.010s

FAILED (errors=1)
(env-pypy) $ py.test tests/test_mu.py::Constructor
================================ test session starts ================================
platform darwin -- Python 2.7.12, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/whit537, inifile: pytest.ini
plugins: xdist-1.15.0, cov-2.4.0
collected 1 items 

tests/test_mu.py .

============================= 1 passed in 0.76 seconds ==============================
(env-pypy) $ which py.test
/Users/whit537/workbench/capitalone/cloud-custodian/env-pypy/bin/py.test
(env-pypy) $ which nosetests
/Users/whit537/workbench/capitalone/cloud-custodian/env-pypy/bin/nosetests
(env-pypy) $
```

**Comment by whit537** [comment]
Yet it is also specific to pypy.

```
(cloud-custodian) $ nosetests tests/test_mu.py:Constructor
.
----------------------------------------------------------------------
Ran 1 test in 0.009s

OK
(cloud-custodian) $ py.test tests/test_mu.py::Constructor
================================ test session starts ================================
platform darwin -- Python 2.7.12, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/whit537, inifile: pytest.ini
plugins: xdist-1.15.0, cov-2.4.0
collected 1 items 

tests/test_mu.py .

============================= 1 passed in 0.81 seconds ==============================
(cloud-custodian) $ which py.test
/Users/whit537/workbench/capitalone/cloud-custodian/bin/py.test
(cloud-custodian) $ which nosetests
/Users/whit537/workbench/capitalone/cloud-custodian/bin/nosetests
(cloud-custodian) $
```

**Comment by whit537** [comment]
> If turned on, PyPy accepts to import a module `x` if it finds a file `x.pyc` even if there is no file `x.py`.
>
>This is the way that CPython behaves, but it is disabled by default for PyPy because it is a common cause of issues

http://doc.pypy.org/en/latest/config/objspace.lonepycfiles.html

😝

**Comment by whit537** [comment]
Uuuhhhh ...

```
(Pdb) l
483             shutil.rmtree(self.bench)
484     
485         def py_with_pyc(self, name):
486             path = os.path.join(self.bench, name)
487             open(path, 'w+').write('42')
488  ->         py_compile.compile(path)
489             return path
490     
491     
492     class Constructor(PycCase):
493     
(Pdb) path
'/var/folders/77/7_nmc1957dv3rqv5l1wr5shh0000gn/T/tmp6ZoKPV/foo.py'
(Pdb) open(path).read()
''
(Pdb)
```

**Comment by whit537** [comment]
Got it. Need to flush the file under pypy.

**Comment by whit537** [comment]
PR submitted.

**Comment by whit537** [comment]
Merged!
