### ISSUE TITLE
[-v] Run mailer & sentry w/ Python 3 changes

### ISSUE THREAD

**Issue by whit537** [whit537/cloud-custodian#25]
Run it under Python 2 to make sure we're not breaking it there.

**Comment by whit537** [comment]
Getting:

```
(cloud-custodian) $ c7n-mailer -c mailer.yml && custodian run -c test-policy.yml -s .
2017-06-15 07:42:11,077 - custodian.lambda - DEBUG - Created custodian lambda archive size: 3.01mb
2017-06-15 07:42:13,159 - custodian.lambda - DEBUG - Updating function: cloud-custodian-mailer config
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/bin/custodian", line 11, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/cli.py", line 398, in main
    command(options)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/commands.py", line 83, in _load_policies
    policies = policies.expand_regions(options.regions)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/policy.py", line 139, in expand_regions
    regions, self.resource_types)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/policy.py", line 91, in get_service_region_map
    for r in session.get_available_regions('s3', partition_name=p):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/boto3/session.py", line 173, in get_available_regions
    allow_non_regional=allow_non_regional)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore-1.5.68-py2.7.egg/botocore/session.py", line 875, in get_available_regions
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore-1.5.68-py2.7.egg/botocore/session.py", line 701, in get_component
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore-1.5.68-py2.7.egg/botocore/session.py", line 897, in get_component
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore-1.5.68-py2.7.egg/botocore/session.py", line 186, in create_default_resolver
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore-1.5.68-py2.7.egg/botocore/loaders.py", line 132, in _wrapper
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore-1.5.68-py2.7.egg/botocore/loaders.py", line 424, in load_data
botocore.exceptions.DataNotFoundError: Unable to load data for: endpoints
(cloud-custodian) $
```

**Comment by whit537** [comment]
```
(cloud-custodian) $ c7n-mailer -c mailer.yml
2017-06-15 07:44:04,088 - custodian.lambda - DEBUG - Created custodian lambda archive size: 3.01mb
2017-06-15 07:44:06,204 - custodian.lambda - DEBUG - Updating function: cloud-custodian-mailer config
(cloud-custodian) $
```

**Comment by whit537** [comment]
Getting "Your password has expired. Contact your administrator to reset the password." from console. Pinged Kapil in private slack for re-up.

**Comment by whit537** [comment]
Mailer confirmed working through https://github.com/capitalone/cloud-custodian/pull/1286.

Trying to get sentry working with https://github.com/capitalone/cloud-custodian/pull/1297 ...

```
(py27) $ SENTRY_DSN=https://dead:beef@sentry.io/123456 c7n-sentry deploy -c config.json
2017-06-19 05:50:55,112: c7n-sentry:INFO Deploying lambda for /aws/lambda/custodian-foo in us-east-1
2017-06-19 05:50:56,642: custodian.lambda:INFO Creating subscription filter for /aws/lambda/custodian-foo
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/bin/c7n-sentry", line 11, in <module>
    load_entry_point('c7n-sentry', 'console_scripts', 'c7n-sentry')()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 517, in main
    options.command(options)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 450, in deploy
    region_name, account, policy, options.sentry_dsn)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 474, in deploy_one
    LambdaManager(session_factory).publish(function)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/lib/python2.7/site-packages/c7n/mu.py", line 237, in publish
    if e.add(func):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/lib/python2.7/site-packages/c7n/mu.py", line 1057, in add
    destinationArn=func.alias or func.arn)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/lib/python2.7/site-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the PutSubscriptionFilter operation: The specified log group does not exist.
(py27) $
```

**Comment by whit537** [comment]
Blech, now I get this other message (which I was seeing before, too, both for here and for mailer when I was testing that before I had my password reset):

```
$ SENTRY_DSN=https://dead:beef@sentry.io/123456 c7n-sentry deploy -c config.json
Traceback (most recent call last):
  File "./bin/c7n-sentry", line 11, in <module>
    load_entry_point('c7n-sentry', 'console_scripts', 'c7n-sentry')()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 517, in main
    options.command(options)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 450, in deploy
    region_name, account, policy, options.sentry_dsn)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 470, in deploy_one
    sentry_dsn=sentry_dsn,
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 343, in get_function
    session_factory, log_groups, pattern)])
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/mu.py", line 1031, in __init__
    self.client = self.session.client('logs')
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore-1.5.68-py2.7.egg/botocore/session.py", line 826, in create_client
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore-1.5.68-py2.7.egg/botocore/session.py", line 701, in get_component
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore-1.5.68-py2.7.egg/botocore/session.py", line 897, in get_component
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore-1.5.68-py2.7.egg/botocore/session.py", line 186, in create_default_resolver
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore-1.5.68-py2.7.egg/botocore/loaders.py", line 132, in _wrapper
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore-1.5.68-py2.7.egg/botocore/loaders.py", line 424, in load_data
botocore.exceptions.DataNotFoundError: Unable to load data for: endpoints
$
```

**Comment by whit537** [comment]
Boto version mismatch? https://github.com/boto/boto3/issues/849

**Comment by whit537** [comment]
Ah, right. Need to use tox-based virtualenv post-https://github.com/capitalone/cloud-custodian/pull/1234. That gets me back to the "specified log group" error.

**Comment by whit537** [comment]
Wrong region.

**Comment by whit537** [comment]
```
(py27) $ SENTRY_DSN=https://dead:beef@sentry.io/123456 c7n-sentry deploy -c config.json --region=us-west-2
2017-06-20 04:05:18,052: c7n-sentry:INFO Deploying lambda for /aws/lambda/custodian-foo in us-west-2
2017-06-20 04:05:18,824: custodian.lambda:INFO Publishing custodian policy lambda function cloud-custodian-sentry
2017-06-20 04:05:19,183: custodian.lambda:INFO Creating subscription filter for /aws/lambda/custodian-foo
(py27) $
```

**Comment by whit537** [comment]
![screen shot 2017-06-20 at 4 14 49 am](https://user-images.githubusercontent.com/134455/27330615-04b4a332-556f-11e7-9747-a422dac0a1b8.png)

**Comment by whit537** [comment]
Okay! Working on master.

**Comment by whit537** [comment]
... and on https://github.com/capitalone/cloud-custodian/pull/1286.
