### ISSUE TITLE
[-v] Fix broken mailer

### ISSUE THREAD

**Issue by whit537** [whit537/cloud-custodian#44]
Coming here from https://github.com/whit537/cloud-custodian/issues/42. Mailer appears broken on master. CloudWatch shows `('Unknown resource type', u'sqs')` followed by:

```
Traceback (most recent call last):
File "/var/task/c7n_mailer/handle.py", line 52, in start_c7n_mailer
mailer_sqs_queue_processor.run(parallel)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 122, in run
self.process_sqs_messsage(sqs_message)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 148, in process_sqs_messsage
to_addrs_to_email_messages_map = email_delivery.get_to_addrs_email_messages_map(sqs_message)
File "/var/task/c7n_mailer/email_delivery.py", line 144, in get_to_addrs_email_messages_map
list(to_addrs)
File "/var/task/c7n_mailer/email_delivery.py", line 170, in get_mimetext_message
body = get_rendered_jinja(to_addrs, sqs_message, resources, self.logger)
File "/var/task/c7n_mailer/utils.py", line 61, in get_rendered_jinja
region=sqs_message.get('region', ''))
File "/var/task/jinja2/environment.py", line 1008, in render
return self.environment.handle_exception(exc_info, True)
File "/var/task/jinja2/environment.py", line 780, in handle_exception
reraise(exc_type, exc_value, tb)
File "/var/task/msg-templates/default.j2", line 5, in top-level template code
{{ format_resource(resource, policy['resource']) }}
File "/var/task/c7n_mailer/utils.py", line 266, in resource_format
return "%s" % format_struct(resource)
File "/var/task/c7n_mailer/utils.py", line 114, in format_struct
json.dump(evt, buf, indent=2)
File "/usr/lib64/python2.7/json/__init__.py", line 190, in dump
fp.write(chunk)
TypeError: unicode argument expected, got 'str'
```

**Comment by whit537** [comment]
```
{u'ApproximateNumberOfMessagesNotVisible': u'0', u'QueueUrl': u'https://us-west-2.queue.amazonaws.com/644160558196/whit537-testing-mailer', u'Policy': u'{"Version":"2012-10-17","Id":"arn:aws:sqs:us-west-2:644160558196:whit537-testing-mailer/SQSDefaultPolicy","Statement":[{"Sid":"Sid1483703606926","Effect":"Allow","Principal":"*","Action":"SQS:*","Resource":"arn:aws:sqs:us-west-2:644160558196:whit537-testing-mailer"}]}', u'MessageRetentionPeriod': u'345600', u'ApproximateNumberOfMessagesDelayed': u'0', u'c7n:MatchedFilters': [u'tag:MailerTest'], u'MaximumMessageSize': u'262144', u'CreatedTimestamp': u'1483525735', u'ApproximateNumberOfMessages': u'3', u'ReceiveMessageWaitTimeSeconds': u'0', u'DelaySeconds': u'0', u'VisibilityTimeout': u'30', u'LastModifiedTimestamp': u'1483703607', u'QueueArn': u'arn:aws:sqs:us-west-2:644160558196:whit537-testing-mailer'}
```

```diff
diff --git a/tools/c7n_mailer/c7n_mailer/deploy.py b/tools/c7n_mailer/c7n_mailer/deploy.py
index bff5212..b954114 100644
--- a/tools/c7n_mailer/c7n_mailer/deploy.py
+++ b/tools/c7n_mailer/c7n_mailer/deploy.py
@@ -72,7 +72,7 @@ def provision(config, session_factory):
         events=[
             CloudWatchEventSource(
                 {'type': 'periodic',
-                 'schedule': 'rate(5 minutes)'},
+                 'schedule': 'rate(1 minute)'},
                 session_factory,
                 prefix="")
         ])
diff --git a/tools/c7n_mailer/c7n_mailer/utils.py b/tools/c7n_mailer/c7n_mailer/utils.py
index cd7a97d..934a9b4 100644
--- a/tools/c7n_mailer/c7n_mailer/utils.py
+++ b/tools/c7n_mailer/c7n_mailer/utils.py
@@ -111,6 +111,7 @@ def get_date_time_delta(delta):
 
 def format_struct(evt):
     buf = StringIO()
+    print(evt)
     json.dump(evt, buf, indent=2)
     return buf.getvalue()
 
```

**Comment by whit537** [comment]
🤔 

```
{ u'ApproximateNumberOfMessagesNotVisible': u'0'
, u'QueueUrl': u'https://us-west-2.queue.amazonaws.com/644160558196/whit537-testing-mailer'
, u'Policy': u'{"Version":"2012-10-17","Id":"arn:aws:sqs:us-west-2:644160558196:whit537-testing-mailer/SQSDefaultPolicy","Statement":[{"Sid":"Sid1483703606926","Effect":"Allow","Principal":"*","Action":"SQS:*","Resource":"arn:aws:sqs:us-west-2:644160558196:whit537-testing-mailer"}]}'
, u'MessageRetentionPeriod': u'345600'
, u'ApproximateNumberOfMessagesDelayed': u'0'
, u'c7n:MatchedFilters': [u'tag:MailerTest']
, u'MaximumMessageSize': u'262144'
, u'CreatedTimestamp': u'1483525735'
, u'ApproximateNumberOfMessages': u'3'
, u'ReceiveMessageWaitTimeSeconds': u'0'
, u'DelaySeconds': u'0'
, u'VisibilityTimeout': u'30'
, u'LastModifiedTimestamp': u'1483703607'
, u'QueueArn': u'arn:aws:sqs:us-west-2:644160558196:whit537-testing-mailer'
 }
```

**Comment by whit537** [comment]
Those all look like unicodes to me. What am I missing?

**Comment by whit537** [comment]
Can I repro in `format_struct`?

**Comment by whit537** [comment]
Yes!

**Comment by whit537** [comment]
```
(Pdb) !list(iterable)
['{', '\n  ', '"foo"', ': ', '"bar"', '\n', '}']
(Pdb)
```

**Comment by whit537** [comment]
`buf` is a `StringIO` therefore it is expecting unicode writes.

**Comment by whit537** [comment]
Futures imports added in 1902ba05b26f31a5d5b326a46a02daaac33f3c22 but then removed again(?!) in 165834d36149629de141158e3d54695f2faaa00d.

**Comment by whit537** [comment]
Looks to me like `resource_format` is only used for logging.

**Comment by whit537** [comment]
No I lied it's used as `format_resource` O.o in the default template:

https://github.com/whit537/cloud-custodian/blob/948170cbf03570af6f4494964ae10f09ed0028f8/tools/c7n_mailer/msg-templates/default.j2#L5

**Comment by whit537** [comment]
Well, we can certainly feed Jinja2 a unicode object. It doesn't need a byte-string.

So `resource_format` can return a unicode.

**Comment by whit537** [comment]
So `format_struct` can return a unicode.

**Comment by whit537** [comment]
https://github.com/whit537/cloud-custodian/blob/948170cbf03570af6f4494964ae10f09ed0028f8/tools/c7n_mailer/c7n_mailer/utils.py#L112-L115

**Comment by whit537** [comment]
So it's right for `buf` to be an `io.StringIO`.

**Comment by whit537** [comment]
But what is `json.dump` doing?

https://docs.python.org/2/library/json.html#json.dump

**Comment by whit537** [comment]
> If `ensure_ascii` is true (the default), all non-ASCII characters in the output are escaped with `\uXXXX` sequences, and the result is a `str` instance consisting of ASCII characters only. If `ensure_ascii` is false, some chunks written to fp may be `unicode` instances. This usually happens because the input contains unicode strings or the `encoding` parameter is used. Unless `fp.write()` explicitly understands `unicode` (as in `codecs.getwriter()`) this is likely to cause an error.

**Comment by whit537** [comment]
https://github.com/capitalone/cloud-custodian/pull/1600

**Comment by whit537** [comment]
Now running through mailer readme again ...

**Comment by whit537** [comment]
Still seeing `Unknown resource type sqs` but not subsequent traceback?

**Comment by whit537** [comment]
Yeah we're good. 👍

**Comment by whit537** [comment]
https://github.com/capitalone/cloud-custodian/pull/1417 updated.

**Comment by whit537** [comment]
Alright Sentry what's up?

```
(Pdb) log_group_name
u'/aws/lambda/custodian-foo'
(Pdb)
```

```
(Pdb) c
2017-09-23 15:19:57,449: custodian.lambda:INFO Creating subscription filter for /aws/lambda/custodian-foo
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/bin/c7n-sentry", line 11, in <module>
    load_entry_point('c7n-sentry', 'console_scripts', 'c7n-sentry')()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 519, in main
    options.command(options)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 450, in deploy
    region_name, account, policy, options.sentry_dsn)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 475, in deploy_one
    LambdaManager(session_factory).publish(function)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/mu.py", line 234, in publish
    if e.add(func):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/mu.py", line 1054, in add
    destinationArn=func.alias or func.arn)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/lib/python2.7/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/lib/python2.7/site-packages/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the PutSubscriptionFilter operation: The specified log group does not exist.
(py27) $
```

![screen shot 2017-09-23 at 3 20 19 pm](https://user-images.githubusercontent.com/134455/30776362-bc7be02c-a072-11e7-8571-c157fb285825.png)

**Comment by whit537** [comment]
Where u from `us-east-1`?

```
(Pdb) l
1046                except ClientError as e:
1047                    if e.response['Error']['Code'] != 'ResourceConflictException':
1048                        raise
1049                # Consistent put semantics / ie no op if extant
1050                import pdb; pdb.set_trace()
1051 ->             self.client.put_subscription_filter(
1052                    logGroupName=group['logGroupName'],
1053                    filterName=func.name,
1054                    filterPattern=self.filter_pattern,
1055                    destinationArn=func.alias or func.arn)
1056
(Pdb) group
{u'arn': u'arn:aws:logs:us-east-1:644160558196:log-group:/aws/lambda/custodian-foo:*', u'logGroupName': u'/aws/lambda/custodian-foo'}
(Pdb) pp group
{u'arn': u'arn:aws:logs:us-east-1:644160558196:log-group:/aws/lambda/custodian-foo:*',
 u'logGroupName': u'/aws/lambda/custodian-foo'}
(Pdb)
```

**Comment by whit537** [comment]
Got it! Have to use `--region=us-west-2` vs. `AWS_DEFAULT_REGION=us-west-2`. 🙈
