### ISSUE TITLE
[-v] Port mailer to py36

### ISSUE THREAD

**Issue by whit537** [whit537/cloud-custodian#47]
PR is in https://github.com/capitalone/cloud-custodian/pull/1417.

**Comment by whit537** [comment]
I'm looking at only using py36 per https://github.com/capitalone/cloud-custodian/pull/1611.

I'm looking at using `ruamel.yaml`per https://github.com/capitalone/cloud-custodian/pull/1546#issuecomment-332479768.

Turns out that ruamel doesn't have an `__init__.py`, which trips up `imp.find_module` as used in `PythonPackageArchive` though not `import`. Hack would be to force-write an `__init__.py` if missing?

Also need to update `add_module` to recurse over dots:

> This function does not handle hierarchical module names (names containing dots). In order to find P.M, that is, submodule M of package P, use find_module() and load_module() to find and load package P, and then use find_module() with the path argument set to P.__path__. When P itself has a dotted name, apply this recipe recursively.

https://docs.python.org/2/library/imp.html#imp.find_module

**Comment by whit537** [comment]
```
(py27) $ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ruamel, imp
>>> imp.find_module('ruamel')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ruamel
>>> open(ruamel.__path__[0]+'/__init__.py', 'w+').write('')
>>> imp.find_module('ruamel')
(None, '/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/lib/python2.7/site-packages/ruamel', ('', '', 5))
>>>
```

**Comment by whit537** [comment]
http://tox.readthedocs.io/en/latest/example/devenv.html

**Comment by whit537** [comment]
lol https://bitbucket.org/hpk42/tox/issues/362/support-multiple-requirementstxt-files

**Comment by whit537** [comment]
😞 

```
Collecting functools32==3.2.3-2 (from -r tools/c7n_mailer/requirements.txt (line 4))
  Using cached functools32-3.2.3-2.zip
    Complete output from command python setup.py egg_info:
    This backport is for Python 2.7 only.
```

**Comment by whit537** [comment]
```
_________________________ ERROR collecting tests/test_s3.py _________________________
.tox/py36/lib/python3.6/site-packages/_pytest/python.py:395: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/py36/lib/python3.6/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:961: in _find_and_load
    ???
<frozen importlib._bootstrap>:950: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:646: in _load_unlocked
    ???
<frozen importlib._bootstrap>:616: in _load_backward_compatible
    ???
.tox/py36/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:212: in load_module
    py.builtin.exec_(co, mod.__dict__)
tests/test_s3.py:27: in <module>
    from c7n.executor import MainThreadExecutor
c7n/executor.py:16: in <module>
    from concurrent.futures import (
.tox/py36/lib/python3.6/site-packages/concurrent/futures/__init__.py:8: in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
E     File "/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py36/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
E       raise exception_type, self._exception, self._traceback
E                           ^
E   SyntaxError: invalid syntax

```

**Comment by whit537** [comment]
https://github.com/agronholm/pythonfutures/issues/41

**Comment by whit537** [comment]
Worked around that and a couple other things.

Do we need to expose runtime to config or can we force `python3.6`?

**Comment by whit537** [comment]
Should probably expose to config.

**Comment by whit537** [comment]
Test matrix:

- local
  - `python2.7`
  - `python3.6`
- `runtime`
  - empty
  - `python2.7`
  - `python3.6`
- ruamel `__init__.py`
  - present
  - absent

**Comment by whit537** [comment]
| n  | local     | config    | remote    | `__init__` | expected  | 
|---:|:----------|:----------|:----------|:-----------|:----------|
|  1 | python2.7 | none      | none      | absent     | python2.7 |
|  2 | python2.7 | none      | none      | present    | python2.7 |
|  3 | python2.7 | none      | python2.7 | absent     | python2.7 |
|  4 | python2.7 | none      | python2.7 | present    | python2.7 |
|  5 | python2.7 | none      | python3.6 | absent     | python2.7 |
|  6 | python2.7 | none      | python3.6 | present    | python2.7 |
|  7 | python2.7 | python2.7 | none      | absent     | python2.7 |
|  8 | python2.7 | python2.7 | none      | present    | python2.7 |
|  9 | python2.7 | python2.7 | python2.7 | absent     | python2.7 |
| 10 | python2.7 | python2.7 | python2.7 | present    | python2.7 |
| 11 | python2.7 | python2.7 | python3.6 | absent     | python2.7 |
| 12 | python2.7 | python2.7 | python3.6 | present    | python2.7 |
| 13 | python2.7 | python3.6 | none      | absent     | python3.6 |
| 14 | python2.7 | python3.6 | none      | present    | python3.6 |
| 15 | python2.7 | python3.6 | python2.7 | absent     | python3.6 |
| 16 | python2.7 | python3.6 | python2.7 | present    | python3.6 |
| 17 | python2.7 | python3.6 | python3.6 | absent     | python3.6 |
| 18 | python2.7 | python3.6 | python3.6 | present    | python3.6 |
| 19 | python3.6 | none      | none      | absent     | python2.7 |
| 20 | python3.6 | none      | none      | present    | python2.7 |
| 21 | python3.6 | none      | python2.7 | absent     | python2.7 |
| 22 | python3.6 | none      | python2.7 | present    | python2.7 |
| 23 | python3.6 | none      | python3.6 | absent     | python2.7 |
| 24 | python3.6 | none      | python3.6 | present    | python2.7 |
| 25 | python3.6 | python2.7 | none      | absent     | python2.7 |
| 26 | python3.6 | python2.7 | none      | present    | python2.7 |
| 27 | python3.6 | python2.7 | python2.7 | absent     | python2.7 |
| 28 | python3.6 | python2.7 | python2.7 | present    | python2.7 |
| 29 | python3.6 | python2.7 | python3.6 | absent     | python2.7 |
| 30 | python3.6 | python2.7 | python3.6 | present    | python2.7 |
| 31 | python3.6 | python3.6 | none      | absent     | python3.6 |
| 32 | python3.6 | python3.6 | none      | present    | python3.6 |
| 33 | python3.6 | python3.6 | python2.7 | absent     | python3.6 |
| 34 | python3.6 | python3.6 | python2.7 | present    | python3.6 |
| 35 | python3.6 | python3.6 | python3.6 | absent     | python3.6 |
| 36 | python3.6 | python3.6 | python3.6 | present    | python3.6 |

**Comment by whit537** [comment]
Alright, looks like remote is overriding config. Sup with that?

**Comment by whit537** [comment]
Oh. 

https://github.com/whit537/cloud-custodian/blob/ead8b158371d82324ec2f9d85f0f324b3d2de591/c7n/mu.py#L351

**Comment by whit537** [comment]
Entered in c18b66351acc384d053ab782fcd7245705d8abd3.

**Comment by whit537** [comment]
No explanation evident there, I guess let's remove that.

**Comment by whit537** [comment]
&rarr; https://github.com/capitalone/cloud-custodian/pull/1638

**Comment by whit537** [comment]
https://github.com/capitalone/cloud-custodian/pull/1638#issuecomment-335439651:

> the reason for the that config delete, is that other runtimes like java, nodejs, etc are explicitly not supported aka previously only one runtime supported. For supporting 2.7 and 3.6 as configurable we'll need to add an additional validate logic to policy lambda mode to ensure folks don't do something silly here, eg. deploy as a dotnet runtime
> 
> before we remove this safety belt can we also get a validate of the runtime modes being just py 2.7 and 3.6 in policy mode lambda.

**Comment by whit537** [comment]
Where is/would the runtime be set in policy mode? Under [`policy.properties`](https://github.com/whit537/cloud-custodian/blob/406ab78b7b873de44e980c4f07fced7c99ebbd72/c7n/schema.py#L152)? How does validation work?

**Comment by whit537** [comment]
https://github.com/whit537/cloud-custodian/blob/406ab78b7b873de44e980c4f07fced7c99ebbd72/tests/test_validation.py

**Comment by whit537** [comment]
Unhelpful. That's a single test for cli validation.

**Comment by whit537** [comment]
More promising:

https://github.com/whit537/cloud-custodian/blob/406ab78b7b873de44e980c4f07fced7c99ebbd72/tests/test_schema.py#L25-L287

**Comment by whit537** [comment]
```
(py27) $ py.test tests/test_schema.py
============================================ test session starts =============================================
platform darwin -- Python 2.7.13, pytest-3.2.2, py-1.4.34, pluggy-0.4.0
rootdir: /Users/whit537/workbench/capitalone/cloud-custodian, inifile: tox.ini
plugins: xdist-1.20.0, forked-0.2, cov-2.5.1
collected 18 items                                                                                            

tests/test_schema.py ..................

========================================= 18 passed in 2.03 seconds ==========================================
(py27) $
```

**Comment by whit537** [comment]
What's the right place in the schema for `runtime`? It only makes sense for deploying a lambda, which isn't always how a policy is run. Where in the policy yaml do we talk about lambda-related things?

**Comment by whit537** [comment]
https://github.com/whit537/cloud-custodian/blob/406ab78b7b873de44e980c4f07fced7c99ebbd72/c7n/mu.py#L642-L652

**Comment by whit537** [comment]
No mention of `role`, etc. in:

https://github.com/whit537/cloud-custodian/blob/406ab78b7b873de44e980c4f07fced7c99ebbd72/c7n/schema.py#L185-L208

**Comment by whit537** [comment]
Back at:

https://github.com/whit537/cloud-custodian/blob/406ab78b7b873de44e980c4f07fced7c99ebbd72/tests/test_mu.py#L406-L422

**Comment by whit537** [comment]
And I guess we want to record differently for 2.7 and 3.6. Where was that? 1546?

**Comment by whit537** [comment]
[Yes](https://github.com/capitalone/cloud-custodian/pull/1546/files#diff-bf2505b21f8c1205b426918f8cf36de3R154).

**Comment by whit537** [comment]
>> importlib.import_module does find it
>>
> Okay, lemme see what I can do ...
>
>```
>>>> ruamel = importlib.import_module('ruamel')
>>>> ruamel.__file__
>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>AttributeError: 'module' object has no attribute '__file__'
>```

https://github.com/capitalone/cloud-custodian/pull/1417#discussion_r145335184

**Comment by whit537** [comment]
Turns out that ruamel is a [namespace package](https://www.python.org/dev/peps/pep-0420/).

**Comment by whit537** [comment]
And what does that mean for us? I guess we have to add support for that to `PythonPackageArchive`?

**Comment by whit537** [comment]
The thing we want to be able to do in the mailer is to add an entire namespace package to the archive.

https://github.com/whit537/cloud-custodian/blob/7d4be91e87dc80f68a3ab4968d0a3d891ed9891f/tools/c7n_mailer/c7n_mailer/deploy.py#L52-L54

**Comment by whit537** [comment]
So we need to notice that a module is a namespace package and add all of the `*.py` under it.

**Comment by whit537** [comment]
What's up with `__path__`? Do we add all of the directories mentioned in there?

**Comment by whit537** [comment]
I'm trying to construct a namespace package in test fixture.

**Comment by whit537** [comment]
https://packaging.python.org/guides/packaging-namespace-packages/

**Comment by whit537** [comment]
Alright, trying to get a test working. Something about `*.pth` files?

**Comment by whit537** [comment]
```
/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/lib/python2.7/site-packages
-rwxr-xr-x    1 whit537  staff  625264 Oct  3 06:10 _ruamel_yaml.so*
drwxr-xr-x    4 whit537  staff     136 Oct 18 09:24 ruamel/
-rw-r--r--    1 whit537  staff     539 Oct  3 06:11 ruamel.ordereddict-0.4.13-py2.7-nspkg.pth
drwxr-xr-x   10 whit537  staff     340 Oct  3 06:11 ruamel.ordereddict-0.4.13.dist-info/
-rw-r--r--    1 whit537  staff     539 Oct  3 06:10 ruamel.yaml-0.14.12-py2.7-nspkg.pth
drwxr-xr-x   10 whit537  staff     340 Oct  3 06:11 ruamel.yaml-0.14.12.dist-info/
$ cat ruamel.yaml-0.14.12-py2.7-nspkg.pth 
import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('ruamel',));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('ruamel', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('ruamel', [os.path.dirname(p)])));m = m or sys.modules.setdefault('ruamel', types.ModuleType('ruamel'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
$
```

**Comment by whit537** [comment]
http://lucumr.pocoo.org/2012/6/22/hate-hate-hate-everywhere/#pth-the-failed-design-that-enabled-it-all

**Comment by whit537** [comment]
Alright, so I think under Python 3 we can just have

```
something-on-pythonpath/foo/bar/__init__.py
```

and `foo` will be a namespace package and `bar` will be a subpackage. But on Python 2 we need a `*.pth` hack:

```
something-on-pythonpath/foo.pth
something-on-pythonpath/foo/bar/__init__.py
```

Ya?

**Comment by whit537** [comment]
```
$ python3
Python 3.6.1 (default, Apr  4 2017, 09:36:47) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.insert(0, '/var/folders/77/7_nmc1957dv3rqv5l1wr5shh0000gn/T/tmpdgL5iw')
>>> import namespace_package
>>> namespace_package
<module 'namespace_package' (namespace)>
>>>
```

**Comment by whit537** [comment]
```
$ python2
Python 2.7.13 (default, Jul 18 2017, 09:17:00) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.insert(0, '/var/folders/77/7_nmc1957dv3rqv5l1wr5shh0000gn/T/tmpdgL5iw')
>>> import namespace_package
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named namespace_package
>>>
```

**Comment by whit537** [comment]
Okay, so working as advertised in Python 3, need to figure out Python 2 ...

**Comment by whit537** [comment]
https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages

But ruamel has no `__init__.py` even under Python 2 (right?).

**Comment by whit537** [comment]
https://github.com/pypa/setuptools/blob/403bfce4ab920823cc4ba0b5ca5ac0d1b213513d/setuptools/namespaces.py

**Comment by whit537** [comment]
Meh, not quite working. Working example?

**Comment by whit537** [comment]
```
(py27) $ cat ruamel
ruamel/                                    ruamel.yaml-0.14.12-py2.7-nspkg.pth
ruamel.ordereddict-0.4.13-py2.7-nspkg.pth  ruamel.yaml-0.14.12.dist-info/
ruamel.ordereddict-0.4.13.dist-info/       
(py27) $ cat ruamel.yaml-0.14.12.dist-info/
DESCRIPTION.rst         METADATA                WHEEL                   namespace_packages.txt
INSTALLER               RECORD                  metadata.json           top_level.txt
(py27) $ cat ruamel.yaml-0.14.12.dist-info/namespace_packages.txt 
ruamel
(py27) $ cat ruamel.yaml-0.14.12
ruamel.yaml-0.14.12-py2.7-nspkg.pth  ruamel.yaml-0.14.12.dist-info/
(py27) $ cat ruamel.yaml-0.14.12-py2.7-nspkg.pth 
import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('ruamel',));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('ruamel', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('ruamel', [os.path.dirname(p)])));m = m or sys.modules.setdefault('ruamel', types.ModuleType('ruamel'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
(py27) $ p
/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/lib/python2.7/site-packages
(py27) $
```

**Comment by whit537** [comment]
Somehow ruamel is a namespace package under Python 2 _without_ an `__init__.py` whatsonever. That's what we need to repro.

**Comment by whit537** [comment]
```
(py27) $ python
Python 2.7.13 (default, Jul 18 2017, 09:17:00) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ruamel
>>> ruamel
<module 'ruamel' (built-in)>
>>> 
(py27) $ python3
Python 3.6.1 (default, Apr  4 2017, 09:36:47) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ruamel
>>> ruamel
<module 'ruamel' (namespace)>
>>>
```

**Comment by whit537** [comment]
https://docs.python.org/2/library/site.html

**Comment by whit537** [comment]
Alright, not looking good. Builds from `sys.{,exec_}prefix`, which are set at compile-time.

**Comment by whit537** [comment]
But cwd tho?

**Comment by whit537** [comment]
No, because `sys.{,exec_}prefix` is the prefix.

**Comment by whit537** [comment]
But virtualenv figures this out somehow.

**Comment by whit537** [comment]
👍

```
(py27) $ pytest tests/test_mu.py -k namespace
============================================ test session starts =============================================
platform darwin -- Python 2.7.13, pytest-3.2.2, py-1.4.34, pluggy-0.4.0
rootdir: /Users/whit537/workbench/capitalone/cloud-custodian, inifile: tox.ini
plugins: xdist-1.20.0, forked-0.2, cov-2.5.1
collected 38 items                                                                                            

tests/test_mu.py 
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB set_trace (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /Users/whit537/workbench/capitalone/cloud-custodian/tests/test_mu.py(571)test_handles_namespace_packages()
-> installer.target = os.path.join(sys.prefix, 'namespace_package.pth')
(Pdb) sys.prefix
'/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/bin/..'
(Pdb)
```

**Comment by whit537** [comment]
Still getting an `ImportError` with ... 🤔

```diff
diff --git a/tests/test_mu.py b/tests/test_mu.py
index 6d4d7fb..78e71bf 100644
--- a/tests/test_mu.py
+++ b/tests/test_mu.py
@@ -554,16 +554,39 @@ class PythonArchiveTest(unittest.TestCase):
     def test_handles_namespace_packages(self):
         bench = tempfile.mkdtemp()
         sys.path.insert(0, bench)
+        pth = os.path.join(
+            sys.prefix, 'lib', 'python{0}.{1}'.format(*sys.version_info),
+            'site-packages', 'test-pth-can-be-removed-nspkg.pth')
         def cleanup():
             del sys.path[0]
             shutil.rmtree(bench)
+            os.unlink(pth)
         self.addCleanup(cleanup)
 
-        dirpath = os.path.join(bench, 'namespace_package', 'subpackage')
-        os.makedirs(dirpath)
-        open(os.path.join(dirpath, '__init__.py'), 'w+').write('42')
+        subpackage = os.path.join(bench, 'namespace_package', 'subpackage')
+        os.makedirs(subpackage)
+        open(os.path.join(subpackage, '__init__.py'), 'w+').write('foo = 42')
 
+        try:
+            from namespace_package.subpackage import foo
+        except ImportError:
+            pass
+        else:
+            raise foo  # linter hack
+
+        from setuptools import namespaces
+        installer = namespaces.Installer()
+        class Distribution: namespace_packages = ['namespace_package']
+        installer.distribution = Distribution()
+        installer.target = pth.replace('-nspkg', '')  # will be added back
+        installer.outputs = []
+        installer.dry_run = False
+        installer.install_namespaces()
         import pdb; pdb.set_trace()
+
+        from namespace_package.subpackage import foo
+        self.assertEqual(foo, 42)
+
         filenames = self.get_filenames('namespace_package')
         self.assertTrue('namespace_package/__init__.py' not in filenames)
         self.assertTrue('namespace_package/subpackage/__init__.py' in filenames)
```

**Comment by whit537** [comment]
😖

```
(Pdb) installer._get_root()
"sys._getframe(1).f_locals['sitedir']"
```

**Comment by whit537** [comment]
I'm trying to understand this. We need the `-nspkg.pth` in the right place, and we need it to point the bench if we can.

https://github.com/pypa/setuptools/blob/403bfce4ab920823cc4ba0b5ca5ac0d1b213513d/setuptools/namespaces.py#L44-L60

**Comment by whit537** [comment]
I don't get `has_mfs` ... only under Python 3.5? What happens below that?

**Comment by whit537** [comment]
I.e. us.

**Comment by whit537** [comment]
I guess `mfs` is [`module_from_spec`](https://docs.python.org/3/library/importlib.html#importlib.util.module_from_spec), and we're falling into `sys.modules.setdefault(%(pkg)r, types.ModuleType(%(pkg)r))`. That's all floo-flah though just to get a module. The important thing is that we append `os.path.join(%(root)s, *%(pth)r)` to `m.__path__`.

**Comment by whit537** [comment]
`root` is `sys._getframe(1).f_locals['sitedir']` and `pth` [is](https://github.com/pypa/setuptools/blob/403bfce4ab920823cc4ba0b5ca5ac0d1b213513d/setuptools/namespaces.py#L73) is `tuple(pkg.split('.'))`.

**Comment by whit537** [comment]
```
(Pdb) l
 68             return "sys._getframe(1).f_locals['sitedir']"
 69
 70         def _gen_nspkg_line(self, pkg):
 71             # ensure pkg is not a unicode string under Python 2.7
 72             import pdb; pdb.set_trace()
 73  ->         pkg = str(pkg)
 74             pth = tuple(pkg.split('.'))
 75             root = self._get_root()
 76             tmpl_lines = self._nspkg_tmpl
 77             parent, sep, child = pkg.rpartition('.')
 78             if parent:
(Pdb) pkg
u'namespace_package'
(Pdb) n
> /Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/lib/python2.7/site-packages/setuptools/namespaces.py(74)_gen_nspkg_line()
-> pth = tuple(pkg.split('.'))
(Pdb) pkg
'namespace_package'
(Pdb) n
> /Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/lib/python2.7/site-packages/setuptools/namespaces.py(75)_gen_nspkg_line()
-> root = self._get_root()
(Pdb) pth
('namespace_package',)
(Pdb) n
> /Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/lib/python2.7/site-packages/setuptools/namespaces.py(76)_gen_nspkg_line()
-> tmpl_lines = self._nspkg_tmpl
(Pdb) root
"sys._getframe(1).f_locals['sitedir']"
(Pdb)
```

**Comment by whit537** [comment]
So what is `sys._getframe(1).f_locals['sitedir']`?

**Comment by whit537** [comment]
Is the pth import getting triggered?

**Comment by whit537** [comment]
```
(py27) $ cat .tox/py27/lib/python2.7/site-packages/test.pth 
import foo; raise heck
(py27) $ python
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/bin/../lib/python2.7/site.py", line 703, in <module>
    main()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/bin/../lib/python2.7/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/bin/../lib/python2.7/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/bin/../lib/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/.tox/py27/bin/../lib/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
ImportError: No module named foo
(py27) $
```

**Comment by whit537** [comment]
Ooooh! Probably not, because that only gets run on Python startup. 🤔

**Comment by whit537** [comment]
Gosh what a mess.

**Comment by whit537** [comment]
Okay, got something: https://github.com/capitalone/cloud-custodian/pull/1677.

**Comment by whit537** [comment]
Mailer is green but manual test fails, can't find ruamel.

**Comment by whit537** [comment]
Uploaded using py27 targeting py27.

**Comment by whit537** [comment]
Hypothesis: we're no longer hacking in an `__init__.py` file, and we're also not installing via *.pth.

**Comment by whit537** [comment]
Seems to be it. https://github.com/capitalone/cloud-custodian/pull/1710

**Comment by whit537** [comment]
Merged! 💃
