### ISSUE TITLE
[-v] Debug broken mailer

### ISSUE THREAD

**Issue by whit537** [whit537/cloud-custodian#9]
> **JohnTheodore:** https://github.com/capitalone/cloud-custodian/blame/master/tools/c7n_mailer/c7n_mailer/deploy.py#L37
> **JohnTheodore:** hmm, this change yesterday is breaking me
> **JohnTheodore:** I checked out the day before, and it works
> **JohnTheodore:** anyone else have issues?
> **JohnTheodore:**
> ```
>/custodian/src/cloud-custodian/tools/c7n_mailer # c7n-mailer -c ./email-config.yml                                                                              
>Traceback (most recent call last):                                              
>  File "/custodian/src/cloud-custodian/tools/c7n_mailer/c7n_mailer/cli.py", line 72, in main                                                                    
>    deploy.provision(config, functools.partial(session_factory, config))        
>  File "/custodian/src/cloud-custodian/tools/c7n_mailer/c7n_mailer/deploy.py", line 74, in provision                                                            
>    archive = get_archive(config)                                               
>  File "/custodian/src/cloud-custodian/tools/c7n_mailer/c7n_mailer/deploy.py", line 38, in get_archive                                                          
>    'memcache')                                                                 
>TypeError: __init__() takes at most 6 arguments (8 given)                       
> /custodian/src/cloud-custodian/tools/c7n_mailer/c7n_mailer/deploy.py(38)get_archive()                                                                         
>-> 'memcache')
>```
> **kapilt** noted, chad had mentioned testing mailer, but apparently there was a gap

**Comment by whit537** [comment]
Looks like there's an old `PythonPackageArchive` stuck in his craw?

**Comment by whit537** [comment]
https://github.com/capitalone/cloud-custodian/blame/0cfa039b55a3d6c893fdb1505d69d834bf5c3e22/tools/c7n_mailer/c7n_mailer/deploy.py#L37

**Comment by whit537** [comment]
Yeah, old version takes six arguments:

https://github.com/capitalone/cloud-custodian/blob/c44e97ce75d5418f973b5a0e7780f1add9687f55/c7n/mu.py#L63-L64

**Comment by whit537** [comment]
> `which -a c7n-mailer` is probably more interesting.

Actually though we can see that it's pulling from `/custodian/src/cloud-custodian/`, and the hypothesis is that while we've got the latest version of `tools/c7n_mailer/c7n_mailer/deploy.py`, from there we're [importing](https://github.com/capitalone/cloud-custodian/blob/0cfa039b55a3d6c893fdb1505d69d834bf5c3e22/tools/c7n_mailer/c7n_mailer/deploy.py#L17-L21) an old version of `PythonPackageArchive`.

**Comment by whit537** [comment]
How would that happen?

**Comment by whit537** [comment]
Well, if I had this to debug locally, I would throw a `set_trace` before https://github.com/capitalone/cloud-custodian/blob/0cfa039b55a3d6c893fdb1505d69d834bf5c3e22/tools/c7n_mailer/c7n_mailer/deploy.py#L36 and look at `PythonPackageArchive.__file__` ...

```
(cloud-custodian) $ c7n-mailer -c mailer.yml 
> /Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_mailer/c7n_mailer/deploy.py(37)get_archive()
-> archive = PythonPackageArchive(
(Pdb) PythonPackageArchive.__file__
*** AttributeError: type object 'PythonPackageArchive' has no attribute '__file__'
(Pdb) mu
*** NameError: name 'mu' is not defined
(Pdb) c7n.mu
*** NameError: name 'c7n' is not defined
(Pdb) from c7n import mu
(Pdb) mu.__file__
'/Users/whit537/workbench/capitalone/cloud-custodian/c7n/mu.py'
(Pdb)
```

**Comment by whit537** [comment]
> It appears you've got a version discrepancy between c7n-mailer and the underlying c7n/mu.py module.
>I'm trying to come up with a hypothesis for how that would occur, with a test for same.
>Anything particular to your environment that might shed some light?

-----------

> global install conflict with virtualenv install?
> along those lines, perhaps output of `custodian version --debug`

**Comment by whit537** [comment]
Closed https://github.com/capitalone/cloud-custodian/issues/1042.
